### ISSUE TITLE
The player is not shown , firefox 42

### ISSUE THREAD

**Issue by leobano** [Instagit/videojs-sublime#19]
when I click on any video file, player not shown,
firefox console gives the following error:

TypeError: OC.joinPaths is not a function

Firefox 42
owncloud 8.1.4
VideoJS Sublime   0.9.8

**Comment by Instagit** [comment]
>TypeError: OC.joinPaths is not a function

Hmm... that function should be provided by ownCloud. I can't test with version 8.1.4, but I'm using Firefox for development and I've been running all updates since 8.1 and never had such a problem.

After a quick search I found this:

https://github.com/owncloud/apps/commit/4c94dd66bffe75756e3bd38fc3c1338cc1cbd783

Could you try replacing that line in the viewer.js and see if it helps?

**Comment by leobano** [comment]
Thanks for the reply, I did not try the solution, since the upgrade to 8.2.1 owncloud the problem was solved.

**Comment by Instagit** [comment]
Ok, good to hear.
